export const event = {
  name: 'event',
  title: 'Event',
  type: 'document',
  groups: [
    { name: 'main', title: 'Main details', default: true },
    { name: 'image', title: 'Image and consent' },
    { name: 'booking', title: 'Booking and price' },
    { name: 'seo', title: 'Search and sharing' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'main',
      description: 'Keep concise. Shown on event cards and listings.',
      validation: (Rule) => Rule.required().max(80),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'main',
      description: 'Auto-generated from the title. Used in the event page URL.',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'date',
      title: 'Date and time',
      type: 'datetime',
      group: 'main',
      description: 'When the event starts. Time shown to visitors in London time.',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'type',
      title: 'Event type',
      type: 'string',
      group: 'main',
      options: {
        list: [
          { title: 'Concert', value: 'concert' },
          { title: 'Community', value: 'community' },
          { title: 'Service', value: 'service' },
          { title: 'Talk', value: 'talk' },
          { title: 'Other', value: 'other' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'description',
      title: 'Short description',
      type: 'text',
      rows: 3,
      group: 'main',
      description: 'Used in event cards and listings. One or two sentences.',
      validation: (Rule) => Rule.required().max(300),
    },
    {
      name: 'longDescription',
      title: 'Full description',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'main',
      description: 'Full description for the event page. Leave blank to fall back to the short description.',
    },
    {
      name: 'image',
      title: 'Image',
      type: 'image',
      group: 'image',
      options: { hotspot: true },
      description: 'Landscape image, ideally 16:9. Add alt text below.',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'imageAlt',
      title: 'Image alt text',
      type: 'string',
      group: 'image',
      description: 'Describe the image for screen readers. e.g. "Choir in stalls at the Sunday Eucharist".',
      validation: (Rule) => Rule.required().max(200),
    },
    {
      name: 'consentConfirmed',
      title: 'Photo consent confirmed',
      type: 'boolean',
      group: 'image',
      description:
        'Tick to confirm that consent is on file for everyone identifiable in the image. Children require written parental consent.',
      initialValue: false,
    },
    {
      name: 'ticketUrl',
      title: 'Booking link',
      type: 'url',
      group: 'booking',
      description: 'TicketSource booking link. Leave blank if the event is free and unbooked.',
    },
    {
      name: 'price',
      title: 'Price',
      type: 'string',
      group: 'booking',
      description: 'e.g. "£15" or "Free, donations welcome".',
    },
    {
      name: 'isFeatured',
      title: 'Feature on homepage',
      type: 'boolean',
      group: 'main',
      initialValue: false,
      description: 'Featured events appear in the "This week at Holy Trinity" section.',
    },
    {
      name: 'seo',
      title: 'SEO',
      type: 'object',
      group: 'seo',
      description: 'Optional. Falls back to the title and short description if left blank.',
      fields: [
        { name: 'title', title: 'SEO title', type: 'string', validation: (Rule) => Rule.max(70) },
        { name: 'description', title: 'SEO description', type: 'text', rows: 2, validation: (Rule) => Rule.max(160) },
      ],
    },
  ],
  preview: {
    select: { title: 'title', date: 'date', media: 'image', type: 'type' },
    prepare({ title, date, media, type }) {
      const when = date ? new Date(date).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : 'No date';
      return { title, subtitle: `${type || 'event'} • ${when}`, media };
    },
  },
  orderings: [
    { title: 'Date (soonest first)', name: 'dateAsc', by: [{ field: 'date', direction: 'asc' }] },
    { title: 'Date (most recent first)', name: 'dateDesc', by: [{ field: 'date', direction: 'desc' }] },
  ],
};
